micronaut:
  application:
    name: testApp
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: todo
    password: todo
    dialect: org.hibernate.dialect.Oracle10gDialect
jpa:
  default:
    packages-to-scan:
      - "todo.app"
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
